<?php

use Drupal\metadata_hex\Model\NodeBinder;
use Drupal\metadata_hex\Service\MetadataBatchProcessor;
use Drupal\Core\Entity\EntityInterface;
use Drupal\metadata_hex\Service\MetadataExtractor;

/**
 * Implements hook_node_insert().
 *
 * Processes newly inserted nodes if they match the configured node types.
 */
function metadata_hex_node_insert(EntityInterface $node) {
  // Ensure the entity is a node.
  if ($node->getEntityTypeId() !== 'node') {
    return;
  }

  // Load the configuration settings.
  $settingsManager = new \Drupal\metadata_hex\Service\SettingsManager();
  $allowed_types = $settingsManager->getAllowedNodeTypes();

  // Check if the node's bundle type is in the allowed types.
  if (is_array($allowed_types) && in_array($node->bundle(), $allowed_types, true)) {
    // Process the node using MetadataBatchProcessor. 
    $nodeBinder = new NodeBinder(\Drupal::service('logger.channel.default'));
    $nodeBinder->init($node);
    $justProcessed = $nodeBinder->getWasNodeJustProcessed();
// echo $justProcessed . ':<<';
// if justProcessed is empty, that means its a stupid test database nothing there shit... i think
    if ($justProcessed !== null && !$justProcessed){
      // echo "was node just processed: " . (int)$nodeBinder->getWasNodeJustProcessed() . PHP_EOL;
      $mdex = new Drupal\metadata_hex\Service\MetadataExtractor(\Drupal::service('logger.channel.default'));
      $mdbp = new Drupal\metadata_hex\Service\MetadataBatchProcessor(\Drupal::service('logger.channel.default'), $mdex);
      $mdbp->processNode($node->id());
    }
  }
}