metadata_hex.settings:
  type: config_object
  label: 'Metadata Hex Settings'
  mapping:
    extraction_settings:
      type: mapping
      label: 'Extraction Settings'
      mapping:
        hook_node_types:
          type: sequence
          label: 'Node types for extraction hooks'
          sequence:
            type: string
        field_mappings:
          type: string
          label: 'Field mappings (File to Drupal)'
        strict_handling:
          type: boolean
          label: 'Strict handling for string comparison'
        flatten_keys:
          type: boolean
          label: 'Flattens metadata keys'
        data_protected:
          type: boolean
          label: 'Protect existing data from being overwritten'
        title_protected:
          type: boolean
          label: 'Protect title from being overwritten'
        available_extensions:
          type: sequence
          label: 'Enabled file extensions'
          sequence:
            type: string

    node_process:
      type: mapping
      label: 'Node Processing Settings'
      mapping:
        bundle_types:
          type: sequence
          label: 'Bundle types to process'
          sequence:
            type: string
        allow_reprocess:
          type: boolean
          label: 'Allow reprocessing of already processed nodes'

    file_ingest:
      type: mapping
      label: 'File Ingest Settings'
      mapping:
        bundle_type_for_generation:
          type: string
          label: 'Bundle type for content generation'
        file_attachment_field:
          type: string
          label: 'Field for attaching files'
        ingest_directory:
          type: string
          label: 'Directory for file ingestion'
