on:
  push:
    branches:
      - main  # Change this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan git.drupal.org >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@git.drupal.org
        shell: bash
        
      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=no -T git@git.drupal.org || exit 1
      
      - name: Deploy
        run: |
          git push git@git.drupal.org:project/metadata_hex.git main
